export const weatherCodeMap = {
    0: "☀️ Céu limpo",
    1: "🌤️ Principalmente limpo",
    2: "⛅ Parcialmente nublado",
    3: "☁️ Nublado",
    45: "🌫️ Nevoeiro",
    48: "🌫️❄️ Nevoeiro com gelo",
    51: "🌦️ Sol, nuvens e garoa fraca",
    53: "🌦️ Sol, nuvens e garoa moderada",
    55: "🌧️ Dia nublado com garoa forte",
    56: "🌧️❄️ Dia nublado com garoa congelante fraca",
    57: "🌧️❄️ Dia nublado com garoa congelante forte",
    61: "🌧️ Dia nublado com chuva fraca",
    63: "🌧️ Dia nublado com chuva moderada",
    65: "🌧️ Dia nublado com chuva forte",
    66: "🌧️❄️ Dia nublado com chuva congelante fraca",
    67: "🌧️❄️ Dia nublado com chuva congelante forte",
    71: "❄️ Neve fraca",
    73: "❄️ Neve moderada",
    75: "❄️ Neve forte",
    77: "🌨️ Grãos de neve",
    80: "🌦️ Sol e pancadas de chuva fracas",
    81: "🌦️ Sol e pancadas de chuva moderadas",
    82: "🌧️ Dia nublado com pancadas de chuva fortes",
    85: "🌨️ Pancadas de neve fracas",
    86: "🌨️ Pancadas de neve fortes",
    95: "⛈️ Trovoada fraca ou moderada",
    96: "⛈️❄️ Trovoada com granizo fraca",
    99: "⛈️❄️ Trovoada com granizo forte"
};
