      - name: Gerar tiles WEBP

        run: |

          mkdir -p tiles

          for file in chuva_dia_*.png
          do

            nome=$(basename "$file" .png)

            echo "Criando GeoTIFF..."

            gdal_translate \
              -of GTiff \
              -a_srs EPSG:4326 \
              -a_ullr -75 6 -30 -35 \
              "$file" \
              "${nome}.tif"

            echo "Reprojetando para WebMercator..."

            gdalwarp \
              -t_srs EPSG:3857 \
              -r bilinear \
              "${nome}.tif" \
              "${nome}_3857.tif"

            echo "Gerando tiles..."

            gdal2tiles.py \
              --xyz \
              --zoom=0-5 \
              --processes=2 \
              --webviewer=none \
              "${nome}_3857.tif" \
              "tiles/${nome}"

          done