- name: Gerar Mapas
  run: |

    rm -rf mapas_hd
    mkdir -p mapas_hd

    python << 'EOF'

    import matplotlib
    matplotlib.use("Agg")

    import xarray as xr
    import numpy as np
    import matplotlib.pyplot as plt
    from scipy.ndimage import gaussian_filter
    from matplotlib.colors import ListedColormap, BoundaryNorm

    ds = xr.open_dataset("ecmwf.grib", engine="cfgrib")

    chuva = ds["tp"] * 1000

    lat = ds.latitude.values
    lon = ds.longitude.values

    lon = np.where(lon > 180, lon - 360, lon)

    ordem = np.argsort(lon)
    lon = lon[ordem]

    chuva = chuva.values[:, :, ordem]

    cores = [
        "#BDBDBD",
        "#81C784",
        "#1B5E20",
        "#4FC3F7",
        "#0D47A1",
        "#FFFF8D",
        "#FDD835",
        "#FB8C00",
        "#E65100",
        "#ff5959",
        "#a10e0e",
        "#8D6E63",
        "#5D4037",
        "#DDA0DD",
        "#9370DB"
    ]

    niveis = [
        1, 3, 6, 10, 15,
        20, 30, 40, 50,
        75, 100, 150,
        200, 300, 400, 1000
    ]

    cmap = ListedColormap(cores)
    norm = BoundaryNorm(niveis, cmap.N)

    acumulado = np.zeros_like(chuva[0])

    for i in range(min(5, chuva.shape[0])):

        acumulado += chuva[i]

        dados = gaussian_filter(acumulado, sigma=1.2)

        fig = plt.figure(figsize=(18, 18), dpi=260)

        ax = plt.axes()

        ax.set_axis_off()

        plt.subplots_adjust(
            left=0,
            right=1,
            top=1,
            bottom=0
        )

        ax.contourf(
            lon,
            lat,
            dados,
            levels=niveis,
            cmap=cmap,
            norm=norm,
            antialiased=True,
            extend="max"
        )

        arquivo = f"mapas_hd/chuva_dia_{i}.png"

        plt.savefig(
            arquivo,
            transparent=True,
            bbox_inches="tight",
            pad_inches=0
        )

        plt.close()

        print(f"Gerado: {arquivo}")

    EOF
  
  run: 

    mkdir -p docs

    cp mapas.html docs/index.html

    cp metadados.json docs/metadados.json

    cp -r mapas_hd docs/mapas_hd

    echo "Arquivos copiados"